// ─── Network+ Abbreviations Reference (generated) ───
#import "abbr-style.typ": *

#set page(paper: "a5", margin: (x: 8mm, top: 10mm, bottom: 12mm),
  footer: context {
    if counter(page).get().first() > 1 [
      #h(1fr)
      #text(size: 7pt, fill: luma(150))[#counter(page).display()]
      #h(1fr)
    ]
  },
)
#set text(font: "Inter", size: 7pt, weight: "medium", fill: rgb("#3d3d3d"))
#set par(leading: 0.5em)

// ─── Cover ───
#align(center + horizon)[
  #block(
    width: 80%,
    inset: 8mm,
    radius: 4mm,
    fill: gradient.linear(rgb("#667eea"), rgb("#764ba2"), angle: 135deg),
  )[
    #align(center)[
      #text(size: 20pt, weight: "bold", fill: white)[Abbreviations]
      #v(2mm)
      #text(size: 11pt, fill: white.transparentize(10%))[CompTIA Network+ N10-009]
    ]
  ]
]

#pagebreak()

#table(
  columns: (auto, 1fr, auto),
  inset: (x: 3pt, y: 2pt),
  stroke: none,
  fill: (_, row) => if row == 0 { accent } else if calc.even(row) { accent-bg } else { none },
  table.header(
    text(fill: white, weight: "bold")[Abbr.],
    text(fill: white, weight: "bold")[Full Name],
    text(fill: white, weight: "bold")[Source],
  ),
  [AAA], [Authentication, Authorization, and Accounting], [4.1-authentication],
  [AC], [Alternating Current], [2.4-power],
  [ACL], [Access Control List], [4.1-security-concepts],
  [ACR], [Attenuation to Crosstalk Ratio], [5.2-cable-issues],
  [AES], [Advanced Encryption Standard], [2.3-wireless-encryption],
  [AFP], [Apple Filing Protocol], [5.5-software-tools],
  [AH], [Authentication Header], [1.4-other-protocols],
  [AIC], [Availability, Integrity, Confidentiality (alternate CIA)], [4.1-security-technologies],
  [AP], [Access Point], [1.2-networking-devices],
  [API], [Application Programming Interface], [],
  [APIPA], [Automatic Private IP Addressing], [1.7-ipv4-addressing],
  [ARP], [Address Resolution Protocol], [1.4-network-communication],
  [ARPANET], [Advanced Research Projects Agency Network], [4.1-authentication],
  [AS], [Autonomous System], [2.1-dynamic-routing],
  [ASIC], [Application-Specific Integrated Circuit], [1.2-networking-devices],
  [BGP], [Border Gateway Protocol], [2.1-dynamic-routing],
  [BNC], [Bayonet Neill-Concelman], [1.5-copper-connectors],
  [BOOTP], [Bootstrap Protocol], [3.4-dhcp],
  [BPDU], [Bridge Protocol Data Unit], [5.3-switching-issues],
  [BSSID], [Basic Service Set Identifier], [2.3-wireless-networking],
  [BYOD], [Bring Your Own Device], [4.1-segmentation-enforcement],
  [CA], [Certificate Authority], [4.1-security-concepts],
  [CAPWAP], [Control and Provisioning of Wireless Access Points], [2.3-wireless-networking],
  [CBC-MAC], [Cipher Block Chaining Message Authentication Code], [2.3-wireless-encryption],
  [CCMP], [Counter Mode with CBC-MAC Protocol], [2.3-wireless-encryption],
  [CCTV], [Closed Circuit Television], [4.1-security-concepts],
  [CDMA], [Code-Division Multiple Access], [1.5-wireless-networking],
  [CDN], [Content Delivery Network], [1.2-networking-functions],
  [CDP], [Cisco Discovery Protocol], [3.2-network-solutions],
  [CIA], [Confidentiality, Integrity, Availability (security triad)], [4.1-security-technologies],
  [CIDR], [Classless Inter-Domain Routing], [1.3-designing-the-cloud],
  [CIFS], [Common Internet File System], [1.4-common-ports],
  [CNAME], [Canonical Name (DNS record)], [3.4-dns-records],
  [CRC], [Cyclic Redundancy Check], [3.2-snmp],
  [DAD], [Duplicate Address Detection], [3.4-ipv6-and-slaac],
  [DAP], [Directory Access Protocol], [4.1-authentication],
  [dBm], [Decibels per Milliwatt], [5.2-hardware-issues],
  [DC], [Direct Current], [2.4-power],
  [DDoS], [Distributed Denial of Service], [4.2-denial-of-service],
  [DFS], [Dynamic Frequency Selection], [2.3-wireless-technologies],
  [DHCP], [Dynamic Host Configuration Protocol], [1.4-common-ports],
  [DKIM], [Domain Keys Identified Mail], [3.4-dns-records],
  [DLC], [Data Link Control], [1.1-osi-model],
  [DNS], [Domain Name System], [1.1-osi-model],
  [DNSSEC], [Domain Name Security Extensions], [3.4-overview-of-dns],
  [DOCSIS], [Data Over Cable Service Interface Specification], [1.5-copper-connectors],
  [DoH], [DNS over HTTPS], [3.4-overview-of-dns],
  [DORA], [Discover, Offer, Request, Acknowledge (DHCP)], [3.4-dhcp],
  [DoS], [Denial of Service], [4.2-denial-of-service],
  [DoT], [DNS over TLS], [3.4-overview-of-dns],
  [DRP], [Disaster Recovery Plan], [3.3-disaster-recovery],
  [DSL], [Digital Subscriber Line], [1.5-copper-connectors],
  [EIGRP], [Enhanced Interior Gateway Routing Protocol], [2.1-dynamic-routing],
  [EMI], [Electromagnetic Interference], [5.2-cable-issues],
  [EOL], [End of Life], [3.1-life-cycle-management],
  [EOS], [End of Support], [3.1-life-cycle-management],
  [ESP], [Encapsulation Security Payload], [1.4-other-protocols],
  [ESSID], [Extended Service Set Identifier], [2.3-wireless-networking],
  [EUI], [Extended Unique Identifier], [1.1-osi-model],
  [FCC], [Federal Communications Commission], [2.3-wireless-technologies],
  [FCS], [Frame Check Sequence], [2.2-vlans-and-trunking],
  [FEP], [Fluorinated Ethylene Polymer], [1.5-copper-cabling],
  [FEXT], [Far-End Crosstalk], [5.2-cable-issues],
  [FHRP], [First Hop Redundancy Protocol], [2.1-routing-technologies],
  [FQDN], [Fully Qualified Domain Name], [1.4-common-ports],
  [FTP], [File Transfer Protocol], [1.1-osi-model],
  [GCMP], [Galois Counter Mode Protocol], [2.3-wireless-encryption],
  [GDPR], [General Data Protection Regulation], [4.1-regulatory-compliance],
  [GMAC], [Galois Message Authentication Code], [2.3-wireless-encryption],
  [GPS], [Global Positioning System], [4.1-security-concepts],
  [GRE], [Generic Routing Encapsulation], [1.4-other-protocols],
  [GSM], [Global System for Mobile Communications], [1.5-wireless-networking],
  [HaaS], [Hardware as a Service], [1.3-cloud-models],
  [HTML], [Hypertext Markup Language], [3.5-vpns],
  [HTTP], [Hypertext Transfer Protocol], [1.1-osi-model],
  [HTTPS], [Hypertext Transfer Protocol Secure], [1.1-osi-model],
  [HVAC], [Heating, Ventilating, and Air Conditioning], [2.4-environmental-factors],
  [IaaS], [Infrastructure as a Service], [1.3-cloud-models],
  [IAM], [Identity and Access Management], [4.1-security-concepts],
  [IBSS], [Independent Basic Service Set], [2.3-network-types],
  [ICMP], [Internet Control Message Protocol], [1.4-other-protocols],
  [ICS], [Industrial Control Systems], [4.1-segmentation-enforcement],
  [ICV], [Integrity Check Value], [1.4-other-protocols],
  [IDF], [Intermediate Distribution Frame], [2.4-installing-networks],
  [IDS], [Intrusion Detection System], [1.2-networking-devices],
  [IEEE], [Institute of Electrical and Electronics Engineers], [1.5-wireless-networking],
  [IETF], [Internet Engineering Task Force], [],
  [IIoT], [Industrial Internet of Things], [4.1-segmentation-enforcement],
  [IKE], [Internet Key Exchange], [1.4-other-protocols],
  [IMAP], [Internet Message Access Protocol], [1.4-common-ports],
  [IoT], [Internet of Things], [1.1-osi-model],
  [IP], [Internet Protocol], [1.1-osi-model],
  [IPAM], [IP Address Management], [3.1-network-documentation],
  [IPS], [Intrusion Prevention System], [1.2-networking-devices],
  [IPSec], [Internet Protocol Security], [1.4-other-protocols],
  [ISAKMP], [Internet Security Association and Key Management Protocol], [1.4-other-protocols],
  [ISL], [Inter-Switch Link], [2.2-vlans-and-trunking],
  [ISP], [Internet Service Provider], [5.5-software-tools],
  [ITU], [International Telecommunications Union], [2.3-wireless-technologies],
  [LACP], [Link Aggregation Control Protocol], [2.2-interface-configurations],
  [LAG], [Link Aggregation Group], [2.2-interface-configurations],
  [LAN], [Local Area Network], [1.2-networking-devices],
  [LC], [Local Connector (fiber)], [1.5-fiber-connectors],
  [LDAP], [Lightweight Directory Access Protocol], [1.4-common-ports],
  [LED], [Light-Emitting Diode], [1.5-optical-fiber],
  [LLDP], [Link Layer Discovery Protocol], [3.2-network-solutions],
  [LTE], [Long-Term Evolution], [1.5-wireless-networking],
  [LTE-A], [Long-Term Evolution Advanced], [1.5-wireless-networking],
  [MAC], [Media Access Control], [1.1-osi-model],
  [MDF], [Main Distribution Frame], [2.4-installing-networks],
  [MDIX], [Medium Dependent Interface Crossover], [5.2-cable-issues],
  [MFA], [Multifactor Authentication], [4.1-authentication],
  [MIB], [Management Information Base], [3.2-snmp],
  [MPLS], [Multiprotocol Label Switching], [],
  [MPO], [Multi-fiber Push On], [1.5-fiber-connectors],
  [MS-SQL], [Microsoft Structured Query Language], [1.4-common-ports],
  [MTBF], [Mean Time Between Failures], [3.3-disaster-recovery],
  [MTP], [Multi-fiber Termination Push-on (Corning brand for MPO)], [1.5-fiber-connectors],
  [MTTR], [Mean Time to Repair], [3.3-disaster-recovery],
  [MTU], [Maximum Transmission Unit], [1.1-osi-model],
  [MX], [Mail Exchanger (DNS record)], [3.4-dns-records],
  [NAC], [Network Access Control], [4.3-device-security],
  [NAS], [Network-Attached Storage], [1.2-networking-devices],
  [NAT], [Network Address Translation], [1.2-networking-devices],
  [NDP], [Neighbor Discovery Protocol], [3.4-ipv6-and-slaac],
  [NEXT], [Near-End Crosstalk], [5.2-cable-issues],
  [NFS], [Network File System], [5.5-software-tools],
  [NFV], [Network Function Virtualization], [1.3-designing-the-cloud],
  [NGFW], [Next-Generation Firewall], [1.2-networking-devices],
  [NIC], [Network Interface Card], [1.3-designing-the-cloud],
  [NS], [Name Server (DNS record)], [3.4-dns-records],
  [NTP], [Network Time Protocol], [1.4-common-ports],
  [NTS], [Network Time Security], [3.4-time-protocols],
  [OID], [Object Identifier], [3.2-snmp],
  [OSI], [Open Systems Interconnection], [1.1-osi-model],
  [OSPF], [Open Shortest Path First], [2.1-dynamic-routing],
  [OT], [Operational Technology], [4.1-segmentation-enforcement],
  [OUI], [Organizationally Unique Identifier], [4.2-mac-flooding],
  [OWE], [Opportunistic Wireless Encryption], [2.3-wireless-networking],
  [PaaS], [Platform as a Service], [1.3-cloud-models],
  [PAT], [Port Address Translation], [2.1-network-address-translation],
  [PBX], [Private Branch Exchange], [],
  [pcap], [Packet Capture (file format)], [5.5-command-line-tools],
  [PCI DSS], [Payment Card Industry Data Security Standard], [4.1-regulatory-compliance],
  [PDU], [Power Distribution Unit], [2.4-power],
  [PII], [Personally Identifiable Information], [4.2-malware],
  [PKI], [Public Key Infrastructure], [4.1-security-concepts],
  [PoE], [Power over Ethernet], [1.2-networking-devices],
  [POP3], [Post Office Protocol v3], [1.1-osi-model],
  [PPTP], [Point-to-Point Tunneling Protocol], [1.1-osi-model],
  [PSK], [Pre-Shared Key], [2.3-wireless-networking],
  [PTP], [Precision Time Protocol], [3.4-time-protocols],
  [PTR], [Pointer (DNS record)], [3.4-dns-records],
  [PVC], [Polyvinyl Chloride], [1.5-copper-cabling],
  [QoS], [Quality of Service], [1.2-networking-devices],
  [QSFP], [Quad Small Form-Factor Pluggable], [1.5-network-transceivers],
  [QSFP+], [Quad Enhanced Small Form-Factor Pluggable], [1.5-network-transceivers],
  [RA], [Router Advertisement], [3.4-ipv6-and-slaac],
  [RADIUS], [Remote Authentication Dial-In User Service], [4.1-authentication],
  [RBAC], [Role-Based Access Control], [4.1-security-concepts],
  [RDP], [Remote Desktop Protocol], [1.4-common-ports],
  [RF], [Radio Frequency], [],
  [RFB], [Remote Frame Buffer], [3.5-remote-access],
  [RFC], [Request for Comments], [1.7-ipv4-addressing],
  [RFID], [Radio-Frequency Identification], [3.1-network-documentation],
  [RIP], [Routing Information Protocol], [2.1-routing-technologies],
  [RJ11], [Registered Jack type 11], [1.5-copper-connectors],
  [RJ45], [Registered Jack type 45], [1.5-copper-connectors],
  [ROM], [Read-Only Memory], [4.2-mac-flooding],
  [RPC], [Remote Procedure Call], [1.1-osi-model],
  [RPO], [Recovery Point Objective], [3.3-disaster-recovery],
  [RS], [Router Solicitation], [3.4-ipv6-and-slaac],
  [RSTP], [Rapid Spanning Tree Protocol], [2.2-spanning-tree-protocol],
  [RTO], [Recovery Time Objective], [3.3-disaster-recovery],
  [SA], [Security Association], [1.4-other-protocols],
  [SaaS], [Software as a Service], [1.3-cloud-models],
  [SAML], [Security Assertion Markup Language], [4.1-authentication],
  [SAN], [Storage Area Network], [1.2-networking-devices],
  [SC], [Subscriber Connector (fiber)], [1.5-fiber-connectors],
  [SCADA], [Supervisory Control and Data Acquisition], [4.1-segmentation-enforcement],
  [SFD], [Start Frame Delimiter], [2.2-vlans-and-trunking],
  [SFP], [Small Form-Factor Pluggable], [1.5-network-transceivers],
  [SFP+], [Enhanced Small Form-Factor Pluggable], [1.5-network-transceivers],
  [SFTP], [Secure File Transfer Protocol], [1.4-common-ports],
  [SIEM], [Security Information and Event Management], [1.4-common-ports],
  [SIP], [Session Initiation Protocol], [1.4-common-ports],
  [SLA], [Service Level Agreement], [3.1-network-documentation],
  [SLAAC], [Stateless Address Autoconfiguration], [3.4-ipv6-and-slaac],
  [SMB], [Server Message Block], [1.4-common-ports],
  [SMTP], [Simple Mail Transfer Protocol], [1.4-common-ports],
  [SNMP], [Simple Network Management Protocol], [1.4-common-ports],
  [SOA], [Start of Authority (DNS record)], [3.4-dns-records],
  [SPAN], [Switched Port Analyzer], [3.2-logs-and-monitoring],
  [SPF], [Sender Policy Framework], [3.4-dns-records],
  [SPI], [Security Parameters Index], [],
  [SQL], [Structured Query Language], [1.4-common-ports],
  [SSH], [Secure Shell], [1.4-common-ports],
  [SSID], [Service Set Identifier], [2.3-wireless-networking],
  [SSL], [Secure Sockets Layer], [1.1-osi-model],
  [SSO], [Single Sign-On], [4.1-authentication],
  [ST], [Straight Tip (fiber connector)], [1.5-fiber-connectors],
  [STP], [Spanning Tree Protocol / Shielded Twisted Pair], [2.2-spanning-tree-protocol],
  [SVI], [Switched Virtual Interface], [2.2-vlans-and-trunking],
  [TACACS], [Terminal Access Control Access-Control System], [4.1-authentication],
  [TACACS+], [Terminal Access Control Access-Control System Plus], [4.1-authentication],
  [TCP], [Transmission Control Protocol], [1.1-osi-model],
  [TFTP], [Trivial File Transfer Protocol], [1.4-common-ports],
  [TIA], [Telecommunications Industry Association], [5.2-cable-issues],
  [TLD], [Top Level Domain], [3.4-overview-of-dns],
  [TLS], [Transport Layer Security], [1.1-osi-model],
  [TOTP], [Time-based One-Time Password], [4.1-authentication],
  [TPC], [Transmit Power Control], [2.3-wireless-technologies],
  [TTL], [Time to Live], [1.2-networking-functions],
  [UDP], [User Datagram Protocol], [1.1-osi-model],
  [UPS], [Uninterruptible Power Supply], [2.4-power],
  [URI], [Uniform Resource Identifier], [4.3-security-rules],
  [URL], [Uniform Resource Locator], [1.2-networking-devices],
  [UTM], [Unified Threat Management], [],
  [UTP], [Unshielded Twisted Pair], [5.2-cable-issues],
  [UUID], [Universally Unique Identifier], [],
  [VIP], [Virtual IP Address], [1.7-ipv4-addressing],
  [VLAN], [Virtual Local Area Network], [2.2-vlans-and-trunking],
  [VLSM], [Variable-Length Subnet Mask], [1.7-calculating-ipv4-subnets-and-hosts],
  [VNC], [Virtual Network Computing], [3.5-remote-access],
  [VNIC], [Virtual Network Interface Card], [1.3-designing-the-cloud],
  [VoIP], [Voice over Internet Protocol], [1.4-common-ports],
  [VPC], [Virtual Private Cloud], [1.3-designing-the-cloud],
  [VPN], [Virtual Private Network], [1.1-osi-model],
  [WAN], [Wide Area Network], [1.2-networking-devices],
  [WEP], [Wired Equivalent Privacy], [2.3-wireless-encryption],
  [WLC], [Wireless LAN Controller], [1.2-networking-devices],
  [WPA], [Wi-Fi Protected Access], [2.3-wireless-encryption],
  [XSS], [Cross-Site Scripting], [1.2-networking-devices],
  [XT], [Crosstalk], [5.2-cable-issues],
)
